language: scala
scala:
  - 2.11.11
jdk:
  - oraclejdk8
  
env:
  - PLAY_VERSION=2.5.16 # Latest 2.1.x
before_script: 
  - wget http://download.playframework.org/releases/play-${PLAY_VERSION}.zip
  - unzip -q play-${PLAY_VERSION}.zip 
script: sbt test #play-${PLAY_VERSION}/sbt test
notifications:
  # Email notifications are disabled
  email: false
